name: Docker Build Image

on: 
  #push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_run:
    workflows: ["Build Python application and Check Vulnerabilities"]
    branches: [main]
    types: 
      - completed
  workflow_dispatch:

defaults:
  run:
    working-directory: api

jobs:
    Docker-build-:
        runs-on: ubuntu-latest
        env:
            URI: ${{ secrets.URI }}
            KEY: ${{ secrets.KEY }}
        steps: 
        
        #- name: Create .env file
          #uses: SpicyPizza/create-envfile@v1.3.0
          #with:
            #envkey_URI: ${{ secrets.COSMOS_URI }}
            #envkey_KEY: ${{ secrets.COSMOS_KEY }}
            #file_name: .env
            #directory: api
            #fail_on_empty: true
            
        #- name: Create .env file
          #run: |
             #touch .env
             #echo URI: ${{ secrets.URI }} >> .env
             #echo KEY: ${{ secrets.KEY }} >> .env
             #cat .env
             
        #- name: Check the location
          #run:
            #pwd
                    
        #- name: List the files
          #run:
            #ls   
        
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: Check the location
          run:
            pwd
                    
        - name: List the files
          run:
            ls  
            
        #- name: Create .env file
          #uses: SpicyPizza/create-envfile@v1.3.0
          #with:
            #envkey_URI: ${{ secrets.COSMOS_URI }}
            #envkey_KEY: ${{ secrets.COSMOS_KEY }}
            #file_name: .env
            #directory: api
            #fail_on_empty: true
            
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            
        #- name: Create .env file
          #run: |
            #touch .env
            #echo URI: ${{ secrets.COSMOS_URI }} >> .env
            #echo KEY: ${{ secrets.COSMOS_KEY }} >> .env
            #cat .env
        
            
        - name: Check the location
          run:
            pwd
            
        - name: List the files
          run:
            ls         
        
        - name: 'Build & Push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.ACR_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -f Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/fenesys:${{ github.run_id }}
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/fenesys:${{ github.run_id }}
    
