name: Container App Build & Deploy in Test Environment

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      -  'main'
      - 'releases/**'
    paths:
    - '**.py'
    - '**.Dockerfile'
    #- '.github/workflows/fx-t-eu-paccd-01-ca-AutoDeployTrigger-eb91212a-1ffd-46b9-a7e0-06f262dfb32a.yml'

  # Allow mannually trigger 
  workflow_dispatch:      
# Setting Working Directory
defaults:
  run:
    working-directory: api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: fxteupaccd01cr.azurecr.io
          username: ${{ secrets.FXTEUPACCD01CA_REGISTRY_USERNAME }}
          password: ${{ secrets.FXTEUPACCD01CA_REGISTRY_PASSWORD }}
                
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_URI: ${{ secrets.COSMOS_URI }}
          envkey_KEY: ${{ secrets.COSMOS_KEY }}
          file_name: .env
          fail_on_empty: true

      - name: Check the .env file
        run: |
          pwd
          ls

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: fxteupaccd01cr.azurecr.io/fx-t-eu-paccd-01-ca:${{ github.sha }}
          file: ./api/Dockerfile
          context: ./api
          
      - name: List files
        run: |
          pwd
          ls
         


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FXTEUPACCD01CA_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n fx-t-eu-paccd-01-ca -g fx-t-eu-paccd-01-rg --server fxteupaccd01cr.azurecr.io --username  ${{ secrets.FXTEUPACCD01CA_REGISTRY_USERNAME }} --password ${{ secrets.FXTEUPACCD01CA_REGISTRY_PASSWORD }}
            az containerapp update -n fx-t-eu-paccd-01-ca -g fx-t-eu-paccd-01-rg --image fxteupaccd01cr.azurecr.io/fx-t-eu-paccd-01-ca:${{ github.sha }}
